// Code generated by `go generate`; DO NOT EDIT.

package ko

type MarketCodeResolver struct {
	localeNames map[string]string
}

func NewMarketCodeResolver() MarketCodeResolver {
	return MarketCodeResolver{
		localeNames: map[string]string{

			"00": "전통시장",

			"01": "대형유통",

			"02": "인터넷",
		},
	}
}

func (r MarketCodeResolver) SupportedCodes() map[string]string {
	return r.localeNames
}

func (r MarketCodeResolver) ResolveCode(c string) (string, bool) {
	localeName, ok := r.localeNames[c]
	return localeName, ok
}
