// Code generated by `go generate`; DO NOT EDIT.

package ko

type RegionCodeResolver struct {
	localeNames map[string]string
}

func NewRegionCodeResolver() RegionCodeResolver {
	return RegionCodeResolver{
		localeNames: map[string]string{

			"0000": "서울",

			"0001": "부산",

			"0002": "대구",

			"0003": "인천",

			"0004": "광주",

			"0005": "대전",

			"0006": "울산",

			"0007": "세종",

			"0008": "수원",

			"0009": "성남",

			"0010": "고양",

			"0011": "용인",

			"0012": "춘천",

			"0013": "강릉",

			"0014": "청주",

			"0015": "천안",

			"0016": "전주",

			"0017": "순천",

			"0018": "포항",

			"0019": "안동",

			"0020": "창원",

			"0021": "김해",

			"0022": "제주",
		},
	}
}

func (r RegionCodeResolver) SupportedCodes() map[string]string {
	return r.localeNames
}

func (r RegionCodeResolver) ResolveCode(c string) (string, bool) {
	localeName, ok := r.localeNames[c]
	return localeName, ok
}
