// Code generated by `go generate`; DO NOT EDIT.

package code

type ItemCodeResolver struct {
	codeToName map[string]string
	nameToCode map[string]string
}

func NewItemCodeResolver() ItemCodeResolver {
	return ItemCodeResolver{
		codeToName: map[string]string{

			"0000": "대파(1kg)",
		},
		nameToCode: map[string]string{

			"대파(1kg)": "0000",
		},
	}
}

func (r ItemCodeResolver) SupportedCodes() map[string]string {
	return r.codeToName
}

func (r ItemCodeResolver) ResolveCode(c string) (string, bool) {
	localeName, ok := r.codeToName[c]
	return localeName, ok
}

func (r ItemCodeResolver) LookupName(n string) (string, bool) {
	code, ok := r.nameToCode[n]
	return code, ok
}
