// Code generated by `go generate`; DO NOT EDIT.

package code

type MarketCodeResolver struct {
	codeToName map[string]string
	nameToCode map[string]string
}

func NewMarketCodeResolver() MarketCodeResolver {
	return MarketCodeResolver{
		codeToName: map[string]string{

			"00": "전통시장",

			"01": "대형유통",

			"02": "인터넷",
		},
		nameToCode: map[string]string{

			"전통시장": "00",

			"대형유통": "01",

			"인터넷": "02",
		},
	}
}

func (r MarketCodeResolver) SupportedCodes() map[string]string {
	return r.codeToName
}

func (r MarketCodeResolver) ResolveCode(c string) (string, bool) {
	localeName, ok := r.codeToName[c]
	return localeName, ok
}

func (r MarketCodeResolver) LookupName(n string) (string, bool) {
	code, ok := r.nameToCode[n]
	return code, ok
}
